#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")
const appDir = path.resolve(__dirname, "../../app")

process.chdir(dir)

import { Script } from "@opencode-ai/script"
import pkg from "../package.json"
import { generateWebAssets } from "./generate-web-assets"

// Step 1: Build web frontend
console.log("Building web frontend...")
await $`bun run build`.cwd(appDir)
console.log("Web frontend built successfully")

// Step 2: Generate embedded web assets
console.log("Generating embedded web assets...")
const distDir = path.resolve(appDir, "dist")
const outputPath = path.resolve(dir, "src/server/web-assets.gen.ts")
await generateWebAssets(distDir, outputPath)

// Step 3: Fetch and generate models.dev snapshot
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Step 4: Load migrations
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

// Step 5: Build binaries
const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  { os: "linux", arch: "arm64" },
  { os: "linux", arch: "x64" },
  { os: "linux", arch: "x64", avx2: false },
  { os: "linux", arch: "arm64", abi: "musl" },
  { os: "linux", arch: "x64", abi: "musl" },
  { os: "linux", arch: "x64", abi: "musl", avx2: false },
  { os: "darwin", arch: "arm64" },
  { os: "darwin", arch: "x64" },
  { os: "darwin", arch: "x64", avx2: false },
  { os: "win32", arch: "x64" },
  { os: "win32", arch: "x64", avx2: false },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) return false
      if (item.avx2 === false) return baselineFlag
      if (item.abi !== undefined) return false
      return true
    })
  : allTargets

await $`rm -rf dist`

if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}

const binaries: Record<string, string> = {}
for (const item of targets) {
  const name = [
    "openresearch",
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")

  console.log(`Building ${name}...`)
  await $`mkdir -p dist/${name}/bin`

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [
      {
        name: "force-node-pdf-parse",
        setup(build) {
          // pdf-parse's "browser" export resolves to a web bundle that inlines pdfjs-dist
          // with web worker dependencies that don't exist in compiled Bun binaries.
          // Force it to use the Node ESM entry which uses pdfjs-dist/legacy instead.
          const pdfParseReal = fs.realpathSync(path.dirname(require.resolve("pdf-parse/package.json")))
          const pdfjsReal = fs.realpathSync(path.resolve(pdfParseReal, "../pdfjs-dist"))
          const pdfjsLegacy = path.resolve(pdfjsReal, "legacy/build")

          build.onResolve({ filter: /^pdf-parse$/ }, () => {
            return { path: path.resolve(pdfParseReal, "dist/pdf-parse/esm/index.js") }
          })

          // pdfjs does `import(this.workerSrc)` which is a runtime dynamic import
          // that can't be resolved by the bundler. Patch it to a static import so
          // Bun can bundle the worker file into the compiled binary.
          build.onLoad({ filter: /pdfjs-dist.*legacy.*pdf\.mjs$/ }, async (args) => {
            let contents = await Bun.file(args.path).text()
            const workerPath = path.resolve(pdfjsLegacy, "pdf.worker.mjs")
            contents = contents.replace(
              `const worker = await import(\n      /*webpackIgnore: true*/\n      /*@vite-ignore*/\n      this.workerSrc)`,
              `const worker = await import(${JSON.stringify(workerPath)})`,
            )
            return { contents, loader: "js" }
          })
        },
      },
    ],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace("openresearch", "bun") as any,
      outfile: `dist/${name}/bin/openresearch`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/web-index.ts"],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      OPENCODE_EMBEDDED_WEB: "true",
    },
  })

  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

console.log(`\nBuild complete: ${Object.keys(binaries).length} target(s)`)
for (const name of Object.keys(binaries)) {
  console.log(`  dist/${name}/bin/openresearch`)
}
