#!/usr/bin/env bun

import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html",
  ".css": "text/css",
  ".js": "application/javascript",
  ".mjs": "application/javascript",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".eot": "application/vnd.ms-fontobject",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".wasm": "application/wasm",
  ".map": "application/json",
  ".txt": "text/plain",
  ".xml": "application/xml",
  ".webmanifest": "application/manifest+json",
}

const TEXT_EXTENSIONS = new Set([
  ".html",
  ".css",
  ".js",
  ".mjs",
  ".json",
  ".svg",
  ".txt",
  ".xml",
  ".map",
  ".webmanifest",
])

function getMimeType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase()
  return MIME_TYPES[ext] || "application/octet-stream"
}

function isTextFile(filePath: string): boolean {
  const ext = path.extname(filePath).toLowerCase()
  return TEXT_EXTENSIONS.has(ext)
}

function walkDir(dir: string, base: string = dir): string[] {
  const files: string[] = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...walkDir(fullPath, base))
    } else {
      files.push(fullPath)
    }
  }
  return files
}

export async function generateWebAssets(distDir: string, outputPath: string) {
  if (!fs.existsSync(distDir)) {
    throw new Error(`Web app dist directory not found: ${distDir}. Run 'bun run build' in packages/app first.`)
  }

  const files = walkDir(distDir)
  const lines: string[] = [
    "// Auto-generated by generate-web-assets.ts - do not edit",
    "// Contains embedded web frontend assets",
    "",
    "export interface WebAsset {",
    "  data: string",
    "  type: string",
    "  encoding: \"utf8\" | \"base64\"",
    "}",
    "",
    "export const webAssets = new Map<string, WebAsset>()",
    "",
  ]

  for (const filePath of files) {
    const relativePath = "/" + path.relative(distDir, filePath).replaceAll("\\", "/")
    const mimeType = getMimeType(filePath)

    if (isTextFile(filePath)) {
      const content = await Bun.file(filePath).text()
      const escaped = JSON.stringify(content)
      lines.push(`webAssets.set(${JSON.stringify(relativePath)}, { data: ${escaped}, type: ${JSON.stringify(mimeType)}, encoding: "utf8" })`)
    } else {
      const content = await Bun.file(filePath).arrayBuffer()
      const base64 = Buffer.from(content).toString("base64")
      lines.push(`webAssets.set(${JSON.stringify(relativePath)}, { data: ${JSON.stringify(base64)}, type: ${JSON.stringify(mimeType)}, encoding: "base64" })`)
    }
  }

  lines.push("")
  await Bun.write(outputPath, lines.join("\n"))
  console.log(`Generated web assets: ${files.length} files embedded into ${outputPath}`)
}

// Run directly
if (import.meta.main) {
  const distDir = path.resolve(__dirname, "../../../app/dist")
  const outputPath = path.resolve(__dirname, "../src/server/web-assets.gen.ts")
  await generateWebAssets(distDir, outputPath)
}
